# Generated by Django 5.0.12 on 2025-02-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionTime',
            field=models.CharField(max_length=500),
        ),
    ]
